# Generated by Django 4.2.1 on 2023-05-08 04:53

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ("puzzleApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clue",
            name="clue_img",
        ),
        migrations.RemoveField(
            model_name="clue",
            name="clue_link",
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=256)),
                ("answer", models.CharField(max_length=100)),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.expressions.Case,
                        related_name="questions",
                        to="puzzleApp.puzzle",
                    ),
                ),
            ],
        ),
    ]
