# Generated by Django 4.2.1 on 2023-05-08 05:20

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ("puzzleApp", "0003_alter_question_puzzle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="puzzle",
            field=models.OneToOneField(
                on_delete=django.db.models.expressions.Case,
                related_name="question",
                to="puzzleApp.puzzle",
            ),
        ),
    ]
